#can take either a json dictionary entry for a comment, or a praw comment object
#Generated by ChatGPT
class _RedditWrapper:
    def __init__(self, source):
        """
        Initialize with either a PRAW Comment object or a dict (from JSON).
        Expected attributes: id, body, author, parent_id, depth
        """
        if isinstance(source, dict):
            self.id = source.get('id')
            self.body = source.get('body')
            self.author = source.get('author')
            self.parent_id = source.get('parent_id')
            self.depth = source.get('depth')
        
        elif hasattr(source, 'body') and hasattr(source, 'parent_id'):
            # Likely a Comment object
            self.id = source.id
            self.body = source.body
            self.author = str(source.author) if source.author else None
            self.parent_id = source.parent_id
            self.depth = getattr(source, 'depth', None)

        elif hasattr(source, 'title') and hasattr(source, 'selftext'):
            # Likely a Submission object
            self.id = source.id
            self.body = f"{source.title}\n\n{source.selftext}".strip()
            self.author = str(source.author) if source.author else None
            self.parent_id = None
            self.depth = 0

        else:
            raise TypeError(f"{source} is an unsupported data type for RedditWrapper")
